### PR TITLE
Fixed compiler warnings

### PR DESCRIPTION
**Pull request by YuukiMinoru**
some generic "variables not used" and some specific unity 5.1 depricated
API warnings have been fixed.

no functional changes were made.
fixed compiler warnings for projects using strict compilation mode.

### CODE REVIEW

**Comment by Joen-UnLogick** [comment]
It's a nice addition, but your changes wont work with 5.2!
So rather than test if it's 5_1 you need to test that it's not 4_6 and not 5_0. This will ensure it still works in 5.2 and later. UMA requires Unity 4.6 or later so you don't have to test versions prior to 4.6.

Also could you please convert the spaces to tabs, this will preserve the uma code formatting.

Thanks

**Comment by YuukiMinoru** [comment]
Ah, you're right, I didn't think of that since the projects I'm using this for are all running on 5.1. 
I've swapped out the UNITY_5_1 for the !UNITY_4_6 && !UNITY_5_0 as you suggested.

I've also gone and replaced the spaces with tabs. I didn't even realise my visual studio was doing that (I'm not sure when 'use spaces' became the default setting for C# projects...)

**Comment by Joen-UnLogick** [comment]
There is the Unity Forum: http://forum.unity3d.com/threads/uma-unity-multipurpose-avatar-on-the-asset-store.219175
But when it comes to actual code changes most discussions happens on our skype chat, we got a channel with 63 people right now. Most are passive uma users who just likes to know they can get a hold of us in case of emergencies. Send me your skype id and I'll add you to the channel.

**Comment by YuukiMinoru** [comment]
Sure, its Yuuki_Minoru@live.com.au

**Pull request merged**
